name: Build and Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a release with current build'
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.11.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.9'

    - name: Install uv
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://astral.sh/uv/install.ps1 -OutFile install.ps1
        .\install.ps1

    - name: Create and activate virtual environment
      shell: pwsh
      run: |
        uv venv zzz-od --python=3.11.9

    - name: Install dependencies
      shell: pwsh
      run: |
        .\zzz-od\Scripts\Activate.ps1
        uv pip install -r requirements-dev.txt
        uv pip install -r requirements-dev-ext.txt
        uv pip compile --annotation-style=line --output-file=requirements-prod.txt requirements-dev.txt
        uv pip install -r requirements-prod.txt

    - name: Download and extract UPX into venv Scripts
      shell: pwsh
      run: |
        $venvScripts = ".\zzz-od\Scripts"
        $upxDir = Join-Path $venvScripts "upx"
        $sourceUpxPath = Join-Path $upxDir "upx-4.2.3-win64" "upx.exe"
        $destinationUpxPath = Join-Path $venvScripts "upx.exe"
        $zipPath = "upx.zip"

        Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v4.2.3/upx-4.2.3-win64.zip" -OutFile $zipPath
        Expand-Archive -Path $zipPath -DestinationPath $upxDir -Force
        Move-Item -Path $sourceUpxPath -Destination $destinationUpxPath -Force
        Remove-Item -Path $upxDir -Recurse -Force

    - name: Build executables
      shell: pwsh
      run: |
        .\zzz-od\Scripts\Activate.ps1
        cd deploy
        pyinstaller "OneDragon Installer.spec"
        pyinstaller "OneDragon Launcher.spec"
        pyinstaller "OneDragon Scheduler.spec"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executables
        path: |
          deploy/dist/OneDragon Installer.exe
          deploy/dist/OneDragon Launcher.exe
          deploy/dist/OneDragon Scheduler.exe

  
